apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: multi-tenancy-gitops
    group: pipeline
    type: git
  name: gitops-repo
data:
  branch: master
  host: github.com
  org: fdut-mq-gitops
  owner: fdut-mq-gitops
  parentdir: .
  protocol: https
  repo: multi-tenancy-gitops-apps
  url: https://github.com/fdut-mq-gitops/multi-tenancy-gitops-apps.git
